#App
app:
  id   : sample01
  domain : http://localhost:8080
  title : Sample
  name : sample
  login: /account/signin
  denied: /account/denied
  logout: /account/signout
  secret: password_encrypt_secret
  anonymous: true

static:
  folder: ../static/
  domain: http://platform.localhost.com/st/static

#session cookie
cookie:
  domain: localhost.com
  name : x-auth
  sessionid : x-sess
  secure : true
  age : 30
  secret: 123456a

#image fs
file:
  folder: /data/image/fs